### PR TITLE
Update Amasty OSC compatibility

### PR DESCRIPTION
**Pull request by gerrits-ecommerce**
Amasty has included some compatibility hooks for this module in their own methods.html file, making that overwrite no longer necessary.
They also changed their shipping overwrite to a mixin and expanded the way that works.

These changes should enable this module to work in the Amasty OSC, though it probably won't look very nice.

### CODE REVIEW

**Comment by gerrits-ecommerce** [comment]
This pull request should fix the problems described in this issue:
https://github.com/tig-nl/postnl-magento2/issues/166

**Comment by tig-jeffreybranderhorst** [comment]
Hi @gerrits-ecommerce 

Is it possible that you contact us on support@tig.nl and send us the amasty extension to test this pull request?  

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST
020 - 21 81 000
*[Wij streven er altijd naar om de hoogste kwaliteit te leveren. Is dat gelukt? Wij horen het graag!|https://search.google.com/local/writereview?placeid=ChIJS-D5wPbixUcRbZw5q5GmJtE]*
Als je een review hebt achter gelaten maak je gelijk kans op een Apple iPad of een coolblue.nl cadeaubon.

**Comment by barryvdh** [comment]
@gerrits-ecommerce @tig-jeffreybranderhorst Did you encounter any issues with the latest version? I'm seeing this error:
 
> require.js:166 Uncaught Error: Script error for: Amasty_Checkout/js/model/cart/totals-processor/default

With amasty/module-single-step-checkout v3.0.8 

If I remove the `totalsProcessor` and related method, I'm getting errors that `shippingRegistry` is not defined.

**Comment by gerrits-ecommerce** [comment]
@barryvdh 

Yeah, an update in Amasty broke this shortly after the release that contained this fix. We made a new pull request that seems to have been accepted but hasn't been included in an official release. 

https://github.com/tig-nl/postnl-magento2/pull/187

**Pull request closed without merging**
