### PR TITLE
Update shipping-mixin.js

### PR DESCRIPTION
**Pull request by gerrits-ecommerce**
On the 6th of July Amasty released an update that changed a dependency in this file. This change makes this file compatible with version 3.0.5.

### CODE REVIEW

**Comment by tig-jaspersmits** [comment]
Thanks @gerrits-ecommerce ! There was a merchant that mentioned this to me. Great to see you already shared the changes required to make it work again. Thanks again!

Kind regards,
Jasper

**Comment by tig-dennisvanderhammen** [comment]
Hi @gerrits-ecommerce,

This has been added to our private repository, and you can expect to see your changes in an upcoming release.
Thank you again for submitting this!

**Comment by gerrits-ecommerce** [comment]
Hi @tig-dennisvanderhammen,

Thank you for letting us know.

**Comment by barryvdh** [comment]
Thank you, I've applied this patch via composer-patches and is seems to work with the latest Amasy checkout:

```
    "extra": {
        "magento-force": "override",
        "patches": {
            "tig/postnl-magento2": {
                "Amasty OSC Compact #187": "https://patch-diff.githubusercontent.com/raw/tig-nl/postnl-magento2/pull/187.diff"
            }
        }
    }
```

Will this be merged/released anytime soon?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @barryvdh,

Yes, we will add this to our newest version of the extension. The extension is now being tested and we are awaiting approval from PostNL.

Have a great day,
Jeffrey

**Comment by tig-dennisvanderhammen** [comment]
Hi @gerrits-ecommerce and @barryvdh ,

Version 1.9.5 of the extension, which contains this PR, just went live. Thank you again for your PR!

**Pull request closed without merging**
