### PR TITLE
Fix incorrect argument in FpdiFactory

### LINKED ISSUE #229: [BUG] Invalid parameter configuration provided for $file argument of TIG\PostNL\Service\Pdf\Fpdi
**To Reproduce**
1. Go to a shipment to generate a PostNL Label, 

**Expected result**
A pdf label for the generated shipment.

**Actual result**
Generates an exception error when clicking on the PostNL - Generate Label button. This also applies to the mass action part for shipments.
Looks like vendor/tig/postnl-magento2/Service/Pdf/FpdiFactory.php gives a String to the constructor of Fdpi class, instead it needs to be an instance of TIG\PostNL\Service\Shipment\Label\File.

postnl-error-stacktrace

**Workaround**
None

** Please complete the following information**
- Magento version: 2.3.5-p1
- PHP version: 7.3.22
- TIG PostNL version: 1.9.5

### PR DESCRIPTION
**Pull request by tdgroot**
Fixes #229

### CODE REVIEW

**Comment by tig-jeffreybranderhorst** [comment]
Hi @tdgroot ,

Just spoke to the team, we are going to add this in our next release.  Thank you for submitting this fix!

Have a great day,
Jeffrey

**Comment by barryvdh** [comment]
@tig-jeffreybranderhorst Do you know when the next release will be, with this included?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @barryvdh ,

The new version is in test phase right now and I cannot give you an release date yet because we first need to wait on the test results. 

Have a great day,
Jeffrey

**Comment by guido7171** [comment]
This one is Merged, https://github.com/tig-nl/postnl-magento2/blob/v1.9.8/Service/Pdf/FpdiFactory.php#L98

thankx!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @guido7171 ,

Indeed, we released the new version just a few hours ago!

Have a great day,
Jeffrey

**Pull request closed without merging**
