### PR TITLE
Add support for Xtento_PdfCustomizer

### PR DESCRIPTION
**Pull request by Tomasz-Silpion**

### CODE REVIEW

**Comment by tig-jaspersmits** [comment]
Hi @Tomasz-Silpion ,

Thanks for submitting this. I'll discuss it with our development team. When there is more information available I'll let you know.

Kind regards,

Jasper
TIG

**Comment by Tomasz-Silpion** [comment]
> @Tomasz-Silpion,
> 
> Please refer to the FoomanCompatibility-classes. Are you sure that using Proxies of Factories isn't a better approach?

FoomanCompatibility classes include Fooman\PdfCustomiser\Block\ShipmentFactoryProxy and \Fooman\PdfCore\Model\PdfRendererFactory made by @fooman in his PdfCustomiser module while I'm neither the owner, nor the developer of Xtento_PdfCustomizer.

I can say only that the solution I made was already successfully tested and is in daily usage on existing Magento 2 store.

**Comment by tig-daanvandenbergh** [comment]
I wasn't suggesting to literally copy/paste his solution. :)

Anyway, thanks for the effort! We'll review it and take it up in a next release.

**Comment by tig-svenluiks** [comment]
Hi @Tomasz-Silpion,

At the moment we can't test this code. Because we don't have the Xtento_PdfCustomiser plugin.
Could you give us access to the plugin?

Kind regards,

Sven
TIG

**Comment by ikk0** [comment]
@tig-svenluiks Hi, XTENTO here. Can confirm the code in the pull request by Tomasz looks good. We will send you an email with the modules source code so you can test it yourself.

**Comment by tig-jaspersmits** [comment]
Hi,

I see we didn't follow up on this. We've tested it, and we confirm the code is working correctly. We will most likely add the code to a future release.

Kind regards,
Jasper

**Pull request closed without merging**
