### PR TITLE
Compatiable with One Step Checkout extension of Mageplaza

### PR DESCRIPTION
**Pull request by NicolasAndersen**
Hi Michiel,

I'm Lucas from Mageplaza. We provide [One Step Checkout ](https://www.mageplaza.com/magento-2-one-step-checkout-extension/)extension for Magento 2 . We want to make postnl extension compatiable with our  [One Step Checkout](https://www.mageplaza.com/magento-2-one-step-checkout-extension/) extension. Please accept this pull request.
Thank you.

Best Regards,
Lucas

### CODE REVIEW

**Comment by tig-michielgerritsen** [comment]
Hello Lucas,

Thanks for your pull request. We would like to accept it, but could you please make sure that the Javascript linter passes? I must note that because this is not commissioned by PostNL we can't give support to merchants when they experience bugs or other issues in future releases.

Michiel

**Comment by NicolasAndersen** [comment]
Hi Michiel,

I'm sorry. I'm not sure about Javascript linter passes. I will check with Javascript linter then make another pull request. Thank you very much.

Best Regards,
Lucas

**Comment by tig-michielgerritsen** [comment]
Hi Lucas,

The solution is pretty simple, just add semicolons to the end of the line:
image

Push a new commit and you should be good to go.

Michiel

**Comment by NicolasAndersen** [comment]
Hi Michiel,

Sorry for later response. I have fixed Javascript linter issue. Please check it.
Thank you.

Best Regards,
Lucas

**Pull request merged**
