### PR TITLE
Remove duplicate method call

### PR DESCRIPTION
**Pull request by bramstroker**

### CODE REVIEW

**Comment by tig-jaspersmits** [comment]
Hi @bramstroker , thanks for sharing this. I'll inform our developers to take a look at it.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
@tig-dennisvanderhammen could you take a look at this?

**Comment by tig-dennisvanderhammen** [comment]
Interesting find, I guess at first glance this shouldn't cause many troubles, but I can imagine if somebody has a plugin on it or something, this could cause issues.

Thank you for submitting this, we'll include this in an upcoming release.

**Comment by tig-vincentthart** [comment]
@bramstroker 

Thank you for sharing this improvement. It was added to version 1.9.6.

Have a great day!

Vincent

**Pull request closed without merging**
